update

diff --git a/wd b/wd
--- a/wd
+++ b/wd
@@ -1,6 +1,6 @@
-#!/bin/env bash
+#!/usr/bin/env bash
 if [[ "$1" ]]; then
 	cd "$HOME/.local/src/$1" || echo "error"
 else
-	cd "$(/bin/ls -d "$HOME"/.local/src/*/ | fzf)" || echo "error"
+	cd "$(/usr/bin/env ls -d "$HOME"/.local/src/*/ | fzf)" || echo "error"
 fi
